#------------------------------------------------------------------------------
# usage: Use tutor to enable the hastexo AWS S3 plugin
#------------------------------------------------------------------------------
name: enable S3 plugin for tutor
description: Github Action to install and enable the Tutor plugin hastexo/tutor-contrib-s3
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    # Notes: OPENEDX_AWS_ACCESS_KEY, OPENEDX_AWS_SECRET_ACCESS_KEY and S3_STORAGE_BUCKET
    #        are stored in EKS kubernetes secrets, viewable from k9s.
    #        example values:
    #          OPENEDX_AWS_ACCESS_KEY: ABDCE123456789OHBBGQ
    #          OPENEDX_AWS_SECRET_ACCESS_KEY: A123456789srJ8lgel+ABCDEFGHIJKabcdefghijk
    #          S3_STORAGE_BUCKET: mrionline-global-prod-storage
    #          S3_BACKUP_BUCKET: mrionline-global-prod-backup
    #          S3_CUSTOM_DOMAIN: cdn.app.mrionline.com
    #          S3_REGION: us-east-2
    #
    # this config depends on a public read-only AWS S3 bucket policy like this:
    # https://github.com/Medality-Health/terraform-openedx/blob/main/components/s3/main.tf#L19
    #
    #      {
    #          "Version": "2012-10-17",
    #          "Statement": [
    #              {
    #                  "Sid": "",
    #                  "Effect": "Allow",
    #                  "Principal": "*",
    #                  "Action": [
    #                      "s3:GetObject*",
    #                      "s3:List*"
    #                  ],
    #                  "Resource": "arn:aws:s3:::prod-mrionline-global-storage/*"
    #              }
    #          ]
    #      }
    #
    - name: fetch S3 secrets from Kubernetes secrets
      shell: bash
      run: |-
        kubectl get secret s3-openedx-storage -n ${{ inputs.namespace }}  -o json | jq  '.data | map_values(@base64d)' | jq -r 'keys[] as $k | "TUTOR_\($k|ascii_upcase)=\(.[$k])"' >> $GITHUB_ENV

    - name: Enable plugin for S3
      shell: bash
      run: |-
        pip install git+https://github.com/hastexo/tutor-contrib-s3@v0.2.2
        tutor plugins enable s3

        tutor config save --set OPENEDX_AWS_ACCESS_KEY="$OPENEDX_AWS_ACCESS_KEY" \
                          --set OPENEDX_AWS_SECRET_ACCESS_KEY="$OPENEDX_AWS_SECRET_ACCESS_KEY" \
                          --set OPENEDX_AWS_QUERYSTRING_AUTH="False" \
                          --set OPENEDX_AWS_S3_SECURE_URLS="False" \
                          --set OPENEDX_MEDIA_ROOT="openedx/media/" \
                          --set S3_STORAGE_BUCKET="$S3_STORAGE_BUCKET" \
                          --set S3_CUSTOM_DOMAIN="$S3_CUSTOM_DOMAIN" \
                          --set S3_REGION="$S3_REGION" \
